import type { NextPage } from "next"
import MainPageLayout from "../components/MainPageLayout/MainPageLayout"

const Home: NextPage = () => {
  return (
    <>
      <h3>Jóvenes Investigadores</h3>
      <h2>Participa en el primer Coloquio de Investigación</h2>
      <p>
        Presenta tus avances de proyectos de taller de investigación II,
        residencia, tésis y de posgrado que cursan la asignatura en seminario II
        de la Maestría en Administración y Sistemas Computacionales
      </p>
    </>
  )
}

export default Home

{
  /* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */
}
